package ua.lviv.lgs.admissionsCommittee.domain;

public enum SubjectsOfAttestation {
	
	MATHEMATICS, UKRAINIAN, ENGLISH, CHEMISTRY, BIOLOGY,PHYSICS,GEOGRATHY,HISTORY,IT,MUSIC,PHYSICAL_EDUCATION,PHILOSOPHY,PHSIHOLOGY

}
